# Generated by Django 5.2.1 on 2025-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('sex', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('family', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('convicted', models.CharField(max_length=50)),
                ('rus_lang', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=100)),
                ('job_duration', models.CharField(max_length=50)),
                ('previous_job', models.TextField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('military_certificate_id', models.CharField(blank=True, max_length=255, null=True)),
                ('military_certificate_type', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
